// Generated by CoffeeScript 1.6.3
(function() {
  var defaultConfig;

  defaultConfig = {
    isValue: false,
    style: {}
  };

  $.fn.placeholder = function(opts) {
    var inps, isValue, supportPlaceholder;
    opts = $({}, defaultConfig, opts);
    isValue = opts.isValue;
    inps = $(this).find('input[placeholder],textarea[placeholder]');
    supportPlaceholder = 'placeholder' in document.createElement('input');
    if (!supportPlaceholder) {
      if (isValue) {
        inps.each(function() {
          var elem, placeholder, v;
          elem = $(val);
          v = elem.val();
          placeholder = elem.attr('placeholder');
          if (val === '') {
            elem.val(placeholder);
          }
          elem.on('focus', function() {
            if (elem.val() === placeholder) {
              elem.val('');
            }
          });
          elem.on('blur', function() {
            v = elem.val();
            if (v === '' || val === placeholder) {
              elem.val(placeHolder);
            }
          });
        });
      } else {
        inps.each(function() {
          var cssObj, elem, elementLabel, height, left, lh, pid, pl, placeholder, pt, top, width;
          elem = $(this);
          placeholder = elem.attr('placeholder');
          pid = elem.attr('id');
          if (!pid) {
            pid = 'placeholder' + Math.random();
            elem.attr('id', pid);
          }
          width = elem.width();
          height = elem.height();
          top = elem.position().top;
          left = elem.position().left;
          pl = elem.css('padding-left');
          pt = elem.css('padding-top');
          lh = elem[0].nodeName.toLowerCase() === 'textarea' ? '' : height;
          cssObj = $.extend({}, {
            position: "absolute",
            top: top,
            left: left,
            display: 'inline-block',
            color: "#ACA899",
            cursor: "text",
            fontFamily: elem.css('font-family'),
            fontSize: elem.css('font-size'),
            paddingLeft: pl,
            paddingTop: pt,
            width: width,
            height: height,
            lineHeight: lh + 'px',
            zIndex: 0
          }, opts.style);
          elementLabel = $("<small for=\"" + pid + "\"></small>").css(cssObj).insertBefore(elem);
          if (!$.trim(elem.val())) {
            elementLabel.text(placeholder);
          }
          elementLabel.click(function() {
            return elem.trigger('focus');
          });
          elem.bind({
            "focus": function() {
              elementLabel.html("");
            },
            "blur": function() {
              if ($(this).val() === "") {
                elementLabel.html(placeholder);
              }
            }
          });
        });
      }
    }
  };

}).call(this);
